# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.1].define(version: 2024_01_30_150739) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"
  enable_extension "postgis"

  create_table "military_geometries", id: false, force: :cascade do |t|
    t.bigint "osm_id"
    t.text "geom_type"
    t.text "landuse"
    t.text "military"
    t.text "building"
    t.text "name"
    t.text "operator"
    t.geometry "geom", limit: {:srid=>4326, :type=>"st_polygon"}
  end

  create_table "planet_osm_line", id: false, force: :cascade do |t|
    t.bigint "osm_id"
    t.text "access"
    t.text "addr:housename"
    t.text "addr:housenumber"
    t.text "addr:interpolation"
    t.text "admin_level"
    t.text "aerialway"
    t.text "aeroway"
    t.text "amenity"
    t.text "area"
    t.text "barrier"
    t.text "bicycle"
    t.text "brand"
    t.text "bridge"
    t.text "boundary"
    t.text "building"
    t.text "construction"
    t.text "covered"
    t.text "culvert"
    t.text "cutting"
    t.text "denomination"
    t.text "disused"
    t.text "embankment"
    t.text "foot"
    t.text "generator:source"
    t.text "harbour"
    t.text "highway"
    t.text "historic"
    t.text "horse"
    t.text "intermittent"
    t.text "junction"
    t.text "landuse"
    t.text "layer"
    t.text "leisure"
    t.text "lock"
    t.text "man_made"
    t.text "military"
    t.text "motorcar"
    t.text "name"
    t.text "natural"
    t.text "office"
    t.text "oneway"
    t.text "operator"
    t.text "place"
    t.text "population"
    t.text "power"
    t.text "power_source"
    t.text "public_transport"
    t.text "railway"
    t.text "ref"
    t.text "religion"
    t.text "route"
    t.text "service"
    t.text "shop"
    t.text "sport"
    t.text "surface"
    t.text "toll"
    t.text "tourism"
    t.text "tower:type"
    t.text "tracktype"
    t.text "tunnel"
    t.text "water"
    t.text "waterway"
    t.text "wetland"
    t.text "width"
    t.text "wood"
    t.integer "z_order"
    t.float "way_area"
    t.geometry "way", limit: {:srid=>4326, :type=>"line_string"}
    t.index ["way"], name: "planet_osm_line_way_idx", using: :gist
  end

  create_table "planet_osm_point", id: false, force: :cascade do |t|
    t.bigint "osm_id"
    t.text "access"
    t.text "addr:housename"
    t.text "addr:housenumber"
    t.text "addr:interpolation"
    t.text "admin_level"
    t.text "aerialway"
    t.text "aeroway"
    t.text "amenity"
    t.text "area"
    t.text "barrier"
    t.text "bicycle"
    t.text "brand"
    t.text "bridge"
    t.text "boundary"
    t.text "building"
    t.text "capital"
    t.text "construction"
    t.text "covered"
    t.text "culvert"
    t.text "cutting"
    t.text "denomination"
    t.text "disused"
    t.text "ele"
    t.text "embankment"
    t.text "foot"
    t.text "generator:source"
    t.text "harbour"
    t.text "highway"
    t.text "historic"
    t.text "horse"
    t.text "intermittent"
    t.text "junction"
    t.text "landuse"
    t.text "layer"
    t.text "leisure"
    t.text "lock"
    t.text "man_made"
    t.text "military"
    t.text "motorcar"
    t.text "name"
    t.text "natural"
    t.text "office"
    t.text "oneway"
    t.text "operator"
    t.text "place"
    t.text "population"
    t.text "power"
    t.text "power_source"
    t.text "public_transport"
    t.text "railway"
    t.text "ref"
    t.text "religion"
    t.text "route"
    t.text "service"
    t.text "shop"
    t.text "sport"
    t.text "surface"
    t.text "toll"
    t.text "tourism"
    t.text "tower:type"
    t.text "tunnel"
    t.text "water"
    t.text "waterway"
    t.text "wetland"
    t.text "width"
    t.text "wood"
    t.integer "z_order"
    t.geometry "way", limit: {:srid=>4326, :type=>"st_point"}
    t.index ["way"], name: "planet_osm_point_way_idx", using: :gist
  end

  create_table "planet_osm_polygon", id: false, force: :cascade do |t|
    t.bigint "osm_id"
    t.text "access"
    t.text "addr:housename"
    t.text "addr:housenumber"
    t.text "addr:interpolation"
    t.text "admin_level"
    t.text "aerialway"
    t.text "aeroway"
    t.text "amenity"
    t.text "area"
    t.text "barrier"
    t.text "bicycle"
    t.text "brand"
    t.text "bridge"
    t.text "boundary"
    t.text "building"
    t.text "construction"
    t.text "covered"
    t.text "culvert"
    t.text "cutting"
    t.text "denomination"
    t.text "disused"
    t.text "embankment"
    t.text "foot"
    t.text "generator:source"
    t.text "harbour"
    t.text "highway"
    t.text "historic"
    t.text "horse"
    t.text "intermittent"
    t.text "junction"
    t.text "landuse"
    t.text "layer"
    t.text "leisure"
    t.text "lock"
    t.text "man_made"
    t.text "military"
    t.text "motorcar"
    t.text "name"
    t.text "natural"
    t.text "office"
    t.text "oneway"
    t.text "operator"
    t.text "place"
    t.text "population"
    t.text "power"
    t.text "power_source"
    t.text "public_transport"
    t.text "railway"
    t.text "ref"
    t.text "religion"
    t.text "route"
    t.text "service"
    t.text "shop"
    t.text "sport"
    t.text "surface"
    t.text "toll"
    t.text "tourism"
    t.text "tower:type"
    t.text "tracktype"
    t.text "tunnel"
    t.text "water"
    t.text "waterway"
    t.text "wetland"
    t.text "width"
    t.text "wood"
    t.integer "z_order"
    t.float "way_area"
    t.geometry "way", limit: {:srid=>4326, :type=>"geometry"}
    t.index ["way"], name: "planet_osm_polygon_way_idx", using: :gist
  end

  create_table "planet_osm_roads", id: false, force: :cascade do |t|
    t.bigint "osm_id"
    t.text "access"
    t.text "addr:housename"
    t.text "addr:housenumber"
    t.text "addr:interpolation"
    t.text "admin_level"
    t.text "aerialway"
    t.text "aeroway"
    t.text "amenity"
    t.text "area"
    t.text "barrier"
    t.text "bicycle"
    t.text "brand"
    t.text "bridge"
    t.text "boundary"
    t.text "building"
    t.text "construction"
    t.text "covered"
    t.text "culvert"
    t.text "cutting"
    t.text "denomination"
    t.text "disused"
    t.text "embankment"
    t.text "foot"
    t.text "generator:source"
    t.text "harbour"
    t.text "highway"
    t.text "historic"
    t.text "horse"
    t.text "intermittent"
    t.text "junction"
    t.text "landuse"
    t.text "layer"
    t.text "leisure"
    t.text "lock"
    t.text "man_made"
    t.text "military"
    t.text "motorcar"
    t.text "name"
    t.text "natural"
    t.text "office"
    t.text "oneway"
    t.text "operator"
    t.text "place"
    t.text "population"
    t.text "power"
    t.text "power_source"
    t.text "public_transport"
    t.text "railway"
    t.text "ref"
    t.text "religion"
    t.text "route"
    t.text "service"
    t.text "shop"
    t.text "sport"
    t.text "surface"
    t.text "toll"
    t.text "tourism"
    t.text "tower:type"
    t.text "tracktype"
    t.text "tunnel"
    t.text "water"
    t.text "waterway"
    t.text "wetland"
    t.text "width"
    t.text "wood"
    t.integer "z_order"
    t.float "way_area"
    t.geometry "way", limit: {:srid=>4326, :type=>"line_string"}
    t.index ["way"], name: "planet_osm_roads_way_idx", using: :gist
  end

  create_table "viirs_fire_events", force: :cascade do |t|
    t.float "latitude"
    t.float "longitude"
    t.float "bright_ti4"
    t.float "scan"
    t.float "track"
    t.datetime "acq_date"
    t.text "satellite"
    t.text "instrument"
    t.text "confidence"
    t.text "version"
    t.float "bright_ti5"
    t.float "frp"
    t.text "daynight"
    t.virtual "geom", type: :geometry, limit: {:srid=>4326, :type=>"geometry"}, as: "st_makepoint(longitude, latitude)", stored: true
  end

end
